name: CARES
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - jupyter
  - notebook
  - ipykernel
  - jupyterlab
  - nb_conda
  - nb_conda_kernels
  - xlrd
  - openpyxl
  - plotly
  - bokeh
  - beautifulsoup4
  - requests
